config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :order_line_items
  resources :orders
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  acts_as_ordered_taggable

  validates :name, presence: true
  validates :price, numericality: true, presence: true

  has_many :order_line_items
  has_many :orders, through: :order_line_items
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_line_items
  has_many :items, through: :order_line_items
  accepts_nested_attributes_for :order_line_items, allow_destroy: true
  belongs_to :user
end

app/models/order_line_item.rb
class OrderLineItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  respond_to :json

  def index
    render 'application/index'
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:searchStr].present?
      searchArr = params[:searchStr].split(",")
      @items = Item.tagged_with(searchArr, :any => true)
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    item_params[:tag_list].present? ? @item.tag_list.add(item_params[:tag_list].split(", ")) : nil
    if !@item.save
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.name = item_params[:name]
    @item.price = item_params[:price]
    item_params[:tag_list].present? ? @item.tag_list.add(item_params[:tag_list].split(", ")) : nil
    if !@item.save
      render json: @item.errors, status: :unprocessable_entity
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:id, :name, :price, :tag_list)
    end
end

app/controllers/order_line_items_controller.rb
class OrderLineItemsController < ApplicationController
  before_action :set_order_line_item, only: [:show, :edit, :update, :destroy]

  # GET /order_line_items
  # GET /order_line_items.json
  def index
    @order_line_items = OrderLineItem.all
  end

  # GET /order_line_items/1
  # GET /order_line_items/1.json
  def show
  end

  # GET /order_line_items/new
  def new
    @order_line_item = OrderLineItem.new
  end

  # GET /order_line_items/1/edit
  def edit
  end

  # POST /order_line_items
  # POST /order_line_items.json
  def create
    @order_line_item = OrderLineItem.new(order_line_item_params)

    respond_to do |format|
      if @order_line_item.save
        format.html { redirect_to @order_line_item, notice: 'Order line item was successfully created.' }
        format.json { render :show, status: :created, location: @order_line_item }
      else
        format.html { render :new }
        format.json { render json: @order_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_line_items/1
  # PATCH/PUT /order_line_items/1.json
  def update
    respond_to do |format|
      if @order_line_item.update(order_line_item_params)
        format.html { redirect_to @order_line_item, notice: 'Order line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line_item }
      else
        format.html { render :edit }
        format.json { render json: @order_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_line_items/1
  # DELETE /order_line_items/1.json
  def destroy
    @order_line_item.destroy
    respond_to do |format|
      format.html { redirect_to order_line_items_url, notice: 'Order line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line_item
      @order_line_item = OrderLineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_item_params
      params.fetch(:order_line_item, {})
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(user_id: current_user.id)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    if !@order.save
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit([:id, :amount, :service_tax, :total_amount,
        order_line_items_attributes: [:item_id, :quantity]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_line_items_helper.rb
module OrderLineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/application/index.html.erb
<!DOCTYPE html>
<html ng-app="restauranteurApp">
  <head>
    <title>Restauranteur</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body ng-controller="RootController">
    <ui-view></ui-view>
  </body>
</html>

app/views/order_line_items/_form.html.erb
<%= form_with(model: order_line_item, local: true) do |form| %>
  <% if order_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_line_item.errors.count, "error") %> prohibited this order_line_item from being saved:</h2>

      <ul>
      <% order_line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_line_items/edit.html.erb
<h1>Editing Order Line Item</h1>

<%= render 'form', order_line_item: @order_line_item %>

<%= link_to 'Show', @order_line_item %> |
<%= link_to 'Back', order_line_items_path %>

app/views/order_line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Line Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_line_items.each do |order_line_item| %>
      <tr>
        <td><%= link_to 'Show', order_line_item %></td>
        <td><%= link_to 'Edit', edit_order_line_item_path(order_line_item) %></td>
        <td><%= link_to 'Destroy', order_line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Line Item', new_order_line_item_path %>

app/views/order_line_items/new.html.erb
<h1>New Order Line Item</h1>

<%= render 'form', order_line_item: @order_line_item %>

<%= link_to 'Back', order_line_items_path %>

app/views/order_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_line_item_path(@order_line_item) %> |
<%= link_to 'Back', order_line_items_path %>